#!/bin/sh
# husky

# Created by Husky v4.2.5 (https://github.com/typicode/husky#readme)
#   At: 7/22/2020, 7:19:29 PM
#   From: /Users/gracz/projects/microservices-dockerized-java11/gateway/node_modules/husky (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
